app:
  database:
    username: root
    password: 1234

  kakao:
    client-id: c586f07818fbf3c70416f67cf702ac76
    client-secret: UV3t4x6B5WWtfTHSQmCGTQ70YkLA2h2B
    redirect-uri: http://localhost:8080/login/oauth2/code/kakao
    admin-key: 5982447af7ca751a908ff709c1dfdca0

  jwt:
    secret: bFNmN+0Eij2CZBnweq8ImC4+BQiXZ6qU5wkfVNfFePRAF19gtpa9oT948Tfmk02cC2OCO+eXi33rNEOzsZ0TGw==